---
deployment:
  tasks:
    - export TODO=/home/yordanbi/to-do
    - export PUBLIC=/home/yordanbi/todo.yordanbian.my.id
    - sed -i 's|../app/Config/Paths.php|../to-do/app/Config/Paths.php|g' public/index.php
    - /bin/cp -r /home/yordanbi/repositories/to-do/* $TODO
    - /bin/cp -r /home/yordanbi/repositories/to-do/public/* $PUBLIC
    - cd $TODO && composer install